
# Ethereum Sepolia
[[EVM]]
ChainID = '$CHAIN_ID_A'

[[EVM.Nodes]]
Name = 'test_1'
WSURL = 'ws://127.0.0.1:$WS_PORT_A'
HTTPURL = 'http://127.0.0.1:$HTTP_PORT_A'

# Arbitrum Sepolia
[[EVM]]
ChainID = '$CHAIN_ID_B'

[[EVM.Nodes]]
Name = "test_2"
WSURL = 'ws://127.0.0.1:$WS_PORT_B'
HTTPURL = 'http://127.0.0.1:$HTTP_PORT_B'

# [EVM.GasEstimator]
# PriceDefault = '20 gwei'
# PriceMax = '115792089237316195423570985008687907853269984665.640564039457584007913129639935 tether'
# PriceMin = '1 gwei'
# LimitDefault = 500000
# LimitMax = 500000
# LimitMultiplier = '1'
# LimitTransfer = 21000
# BumpMin = '5 gwei'
# BumpPercent = 20
# BumpThreshold = 3
# EIP1559DynamicFees = false
# FeeCapDefault = '100 gwei'
# TipCapDefault = '1 wei'
# TipCapMin = '1 wei'

[EVM.Transactions]
ForwardersEnabled = false

[Feature]
LogPoller = true

[OCR2]
Enabled = true
ContractPollInterval = "15s"

[OCR]
Enabled = false
TransmitterAddress = '$TRANSMITTER_ADDRESS'

[P2P.V2]
Enabled = true
# Different per node
ListenAddresses = ["127.0.0.1:8001"]

[WebServer]
# Different per node
# Adjust accordingly in your local setup
HTTPPort = 6688

[WebServer.TLS]
CertPath = ''
ForceRedirect = false
Host = ''
HTTPSPort = 0
KeyPath = ''

[Log]
Level = 'info'
