
# Ethereum Sepolia
[[EVM]]
ChainID = '11155111'

[[EVM.Nodes]]
Name = 'sepolia_1'
WSURL = 'wss://127.0.0.1:8546'
HTTPURL = 'http://127.0.0.1:8545'

# Arbitrum Sepolia
[[EVM]]
ChainID = '421614'

[[EVM.Nodes]]
Name = "arbitrum_sepolia_1"
WSURL = 'wss://127.0.0.1:8646'
HTTPURL = 'http://127.0.0.1:8645'

[EVM.Transactions]
ForwardersEnabled = false

[Feature]
LogPoller = true

[OCR2]
Enabled = true
ContractPollInterval = "15s"

[OCR]
Enabled = false
TransmitterAddress = '0x3605Ca39aC83b8F559B64C453feC6A22AEF99259'

[P2P.V2]
Enabled = true
# Different per node
ListenAddresses = ["127.0.0.1:8001"]

[WebServer]
# Different per node
# Adjust accordingly in your local setup
HTTPPort = 6688

[WebServer.TLS]
CertPath = ''
ForceRedirect = false
Host = ''
HTTPSPort = 0
KeyPath = ''

[Log]
Level = 'info'
